server:
  port:  8200
spring:
  application:
    name:  shop-login
  redis:
    host: 192.168.131.132
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
    ssl: false
  activemq:
    broker-url:  tcp://192.168.131.132:61616
    in-memory:  true
    pool:
      enable:  true
eureka:
  client:
    service-url.defaultZone:  http://localhost:8010/eureka/